### ISSUE TITLE
Didn't figure out how to use it

### ISSUE THREAD

**Issue by moalmalik** [h4ck-rOOt/Lynda-Decryptor#5]
hello
Am trying to figure out how to use your Lunda decryptor but I can't find any guides or How to use anywhere.

Can you please help me.

I used to have a premium Lynda account and used the offline desktop app to download my courses.
now my account is closed and I can't access these courses i found the folder that contains them on my desktop and i need to be able to review them without the need to use any Lynda account.

thank you

**Comment by h4ck-rOOt** [comment]
Hello @moalmalik,

you can use this program by just download it.
Now you have to open a console window by pressing `windows + r` and `cmd`
Navigate to the folder where the program is located.
After that you have to type `LyndaDecryptor /D [DirectoryWhereYourLyndaFilesAre]` and replace the part "DirectoryWhereYourLyndaFilesAre" with the directory containing your lynda files.

hope this would help you using the decryptor

**Comment by sathvikcheela** [comment]
I tried the same but I am not able to decrypt it.

Output:
----------
C:\Users\cheel\Downloads>LyndaDecryptor.exe /D "F:\lynda\502656"
[ARGS] Changing mode to Folder decryption!
[START] Init Decryptor...
[START] Decryptor successful initalized!

Decryption completed!

Press any key to exit the program...

**Comment by Vijaysinh13** [comment]
same thing happen with me like sathvikcheela


C:\Users\USERNAME\Desktop\Lynda_v1.2>LyndaDecryptor /D "C:\Users\USERNAME\AppData\Local\Packages\lynda.com.lynda.com_0dmhem0sv94sr\LocalState\offline\521231" /DB "C:\Users\USERNAME\AppData\Local\Packages\lynda.com.lynda.com_0dmhem0sv94sr\LocalState\db.sqlite" /OUT "E:\OUTPUT_PATH"

[ARGS] Changing mode to Folder decryption!
[START] Init Decryptor...
[START] Decryptor successful initalized!

[DB] Creating db connection...
[DB] DB successfully connected and opened!

Decryption completed!

Press any key to exit the program...

**Comment by KTsarlz** [comment]
@Vijaysinh13 Try reading other issues I believe it was fixed there, esp the ones with a lot of interaction

**Comment by joepolask86** [comment]
Thanks working perfectly. Very fast also.

**Comment by bubbabr** [comment]
Hi @h4ck-rOOt 

Thanks for making this available.  I read you reply to @moalmalik but I'm still really confused.  I'm on a Mac.  I have the files on my computer here: /Users/[MY HOMEFOLDER]/repo/Lynda-Decryptor

I open a terminal session, and type cd /Users/MY HOMEFOLDER/repo/Lynda-Decryptor and hit enter.  In the next line I enter LyndaDecryptor /D /Users/MY HOMEFOLDER/Desktop/lyndafiles and I get the response: -bash: LyndaDecryptor: command not found

So haven't made any progress at all!  Would appreciate any help on this.

Many thanks

**Comment by Dev-iL** [comment]
@bubbabr Mac isn't supported currently (afaik); see #14 . Obviously it doesn't work because you don't have an executable that can run on Mac.. You have to compile it first...

**Comment by bubbabr** [comment]
Thanks @Dev-iL.   I don't suppose you would walk me through the steps in a bit more detail?

I went in the Terminal in Windows to my LyndaDecryptor folder: cd C:\Users\Charlie\Desktop\332\Lynda-Decryptor

Then on the new Terminal line I entered: LyndaDecryptor /D C:\Users\Charlie\Desktop\Lynda\Omnifocus ios\Encrypted\386384

But I still get: 'LyndaDecryptor' is not recognized as an internal or external command, operable program or batch file

I'm completely new to this so I'm sure there's lots of steps I haven't done and should have.  I've tried searching for various guides on how to get started with GitHub, but haven't understood much.  Grateful for any help!

**Comment by Dev-iL** [comment]
@bubbabr GitHub is pretty much just a place for storing files and discussing changes to them.

It sounds like you're still trying to run the decryptor without having an executable available. Make sure you download one of the `.zip` files from [the releases page](https://github.com/h4ck-rOOt/Lynda-Decryptor/releases "e.g. Lynda_v1.2.zip") or [this comment](https://github.com/h4ck-rOOt/Lynda-Decryptor/issues/8#issuecomment-259764764) so that you have an executable (`.exe`) in the active folder... Then the command should work.

**Comment by bubbabr** [comment]
Many thanks @Dev-iL, got it working now!  Really appreciate your help.

I noticed also that the readme file's been expanded recently and that it now gives usage guidance and lists different commands.  Now that I know you need an exe to run the program (ah, small victories!), I have another question related to GitHub projects with a view to exploring them more in the future.  

Assuming there are no usage notes available, is there a certain place to look within the files where the commands for each program can be found?  For example, in the case of this program, is there somewhere where it lists the LyndaDecryptor /D command within the code and explains what it does?  Or is it listed and you're expected to use your programming knowledge to understand its function?

One final thing I'm wondering about is how you compile and recompile - do these terms refer to generating an executable out of the bare bones of code?  And is it right that you may need different software to compile code depending on what programming language its written in?

Thanks a lot

**Comment by h4ck-rOOt** [comment]
Thanks to @Dev-iL for giving some sort of support and answering questions.

@bubbabr The usual way to get those infos is running a program without parameters... most of the command line programs for windows, linux and mac will show usage info, if you do so. It's an known standard within the developer community to do so.

At the easiest explaination level, compiling is the process of taking code as an input via a compiler, produces platform dependend objects (linking them to os functions like open a file) and producing an executable. In C# there is a little difference you can see here:
![Compilation C#](http://images.slideplayer.com/23/6837692/slides/slide_6.jpg)

First of all, the compiler takes code as an input, produces il-code which refers to the msil (microsoft intermediate language). The output will always be a .exe or .dll. On Windows you could just double click  and run it, or call it from the console. Every OS need a virtual machine (CLR) to run MSIL-compiled-code (for mac this is delivered with mono or dotnetcore). The vm is obviously not a compiler, it is an interpreter for IL-Code (sometimes referred as recompiler, just-in-time-compiler, ...). 

It is **NOT** language dependent, nor does it dependent on which tool you are using to compile this code. It depends on which platform you are using and having some sort of runtime installed to execute thos programs.

So if you need further information on this topic, feel free to read this [Wiki (CIL)](https://en.wikipedia.org/wiki/Common_Intermediate_Language) or [Wiki (C#)](https://en.wikipedia.org/wiki/C_Sharp_(programming_language))

I hope this will clarify the situation and helps you to understand whats going on behind the scene.

**Comment by bubbabr** [comment]
Thanks @h4ck-rOOt for the info, will do some further reading.  Much appreciated!

**Comment by IronAsaf** [comment]
Hey there,

I am completely new to basically everything here. I have a premium account of Lynda and all, but I need a converted course for a offline computer. So basically, I downloaded the .zip file, and I ran the LyndaDecryptor.exe (as admin just in case), and opened up the cmd (winkey + r) and I get the error "bubbabr" got before
![1_cmd](https://cloud.githubusercontent.com/assets/25687838/22828349/6515b5a2-efa5-11e6-8f25-f7578e2b170c.png)


Now I am pretty sure the file I downloaded is indeed compiled so I don't think I need to compile it.


I am pretty sure I am doing a lot of things wrong, can you guide a lost man back to reality here?

Thanks in advanced to all!

**Comment by bubbabr** [comment]
From one novice to another @IronAsaf did you make sure you first navigated in the command prompt to the folder where LyndaDecryptor.exe is located? i.e. in the command prompt window, you need to enter: cd [path to folder where LyndaDecryptor.exe is]
and then enter /D [folder with Lynda videos]

**Comment by IronAsaf** [comment]
@bubbabr Ok so I did not do that, now that I tried it I got a different problem - 


Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Asaf_MSI>cd C:\Users\Asaf_MSI\Downloads\LyndaDecryptor

C:\Users\Asaf_MSI\Downloads\LyndaDecryptor>/F C:\Users\Asaf_MSI\Desktop\Works an
d Projects\Videos\Lynda Decrypter
'/F' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Asaf_MSI\Downloads\LyndaDecryptor>LyndaDecryptor /F C:\Users\Asaf_MSI\D
esktop\Works and Projects\Videos\Lynda Decrypter
**[START] Error occured: Input file is missing or not specified!**

Usage (Directory):   LyndaDecryptor /D PATH_TO_FOLDER [OPTIONS]
Usage (File): LyndaDecryptor /F ENCRYPTED_FILE   DECRYPTED_FILE [OPTIONS]


Flags:
        /D      Source files are located in a folder.
        /F      Source and Destination file are specified.
        /DB [PATH]      Search for Database or specify the location on your syst
em.
        /RM     Removes all files after decryption is complete.
        /OUT [PATH]     Specifies an output directory instead of using default d
irectory.

Press any key to exit the program...

C:\Users\Asaf_MSI\Downloads\LyndaDecryptor>LyndaDecryptor /D C:\Users\Asaf_MSI\A
ppData\Local\lynda.com\Lynda.com Desktop App\offline\ldc_dl_courses\81266
**[ARGS] The directory path is missing...

[START] Error occured: Directory path is missing or specified directory was not
found!**

Usage (Directory):   LyndaDecryptor /D PATH_TO_FOLDER [OPTIONS]
Usage (File): LyndaDecryptor /F ENCRYPTED_FILE   DECRYPTED_FILE [OPTIONS]


Flags:
        /D      Source files are located in a folder.
        /F      Source and Destination file are specified.
        /DB [PATH]      Search for Database or specify the location on your syst
em.
        /RM     Removes all files after decryption is complete.
        /OUT [PATH]     Specifies an output directory instead of using default d
irectory.

Press any key to exit the program...

C:\Users\Asaf_MSI\Downloads\LyndaDecryptor>LyndaDecryptor /F C:\Users\Asaf_MSI\A
ppData\Local\lynda.com\Lynda.com Desktop App\offline\ldc_dl_courses\81266 C:\Use
rs\Asaf_MSI\Desktop\Works and Projects\Videos\Lynda Decrypter
**[START] Error occured: Input file is missing or not specified!**

Usage (Directory):   LyndaDecryptor /D PATH_TO_FOLDER [OPTIONS]
Usage (File): LyndaDecryptor /F ENCRYPTED_FILE   DECRYPTED_FILE [OPTIONS]


Flags:
        /D      Source files are located in a folder.
        /F      Source and Destination file are specified.
        /DB [PATH]      Search for Database or specify the location on your syst
em.
        /RM     Removes all files after decryption is complete.
        /OUT [PATH]     Specifies an output directory instead of using default d
irectory.

Press any key to exit the program...

**Comment by bubbabr** [comment]
OK @IronAsaf I'm not sure what exactly the problem is, but let me lay out in clearer steps what works for me (for example, I don't use the /F command). 

1. In command prompt, enter text (without quotes): 'cd [folder with LyndaDecryptor.exe in]' and press Enter
2. In new command prompt line, enter text (without quotes): 'LyndaDecryptor /D [folder with Lynda videos in it]' and press Enter

At this point (for me) decryption starts and completes (with decrypted video staying in same folder as original encrypted video).  Hope that helps - if it doesn't, afraid you'll need to wait for someone else to give some advice.

**Comment by IronAsaf** [comment]
@bubbabr Thanks for all the help! Now, I do still get the same thing, but I want to believe that maybe the source folder is not the one I need. 

Then again it's the only place with a .lynda extension.

**Comment by shaikatray** [comment]
Thanks a lot. Worked like a charm! Really very fast!

**Comment by IronAsaf** [comment]
I feel stupid, may I cry now? May I?!

So basically after a month I finally had time again to test this out again. 
So my issue was that it kept saying :
:no_entry:**[ARGS] The directory path is missing...

:no_entry:[START] Error occured: Directory path is missing or specified directory was not
found!**

The reason for that is such - I did not add quotation marks around the path.

I did - 
LyndaDecryptor /D [folder with Lynda videos in it]

But actually it needs to be - 

LyndaDecryptor /D "folder with Lynda videos in it"


I just wanted to post this for all those poor bastards in the future that ended up like me ;)

**Comment by 522422748** [comment]
I tried the same but I am not able to decrypt it.

![capture](https://user-images.githubusercontent.com/38894421/39493880-34f5dc9c-4db6-11e8-8a00-4c1857777fa3.JPG)

**Comment by edypraveen** [comment]
Thanks for Sharing!! It's working fine !!

**Comment by betterfuturewe** [comment]
I use Allavsoft to download Lynda videos offline to mp4 or mp3.
It still works.

**Comment by rzw-gh** [comment]
Contact me on telegram 
my id: t.me/pyc0der

i'll tell you how to download lynda or udemy courses
